import random

import clip
import torch
from imagenetv2_pytorch import ImageNetV2Dataset
from rtpt import RTPT
from tqdm import tqdm
from transformers import (CLIPTextModelWithProjection,
                          CLIPTokenizer, CLIPVisionModelWithProjection)


def compute_acc(poisoned_text_encoder=None):
    imagenet_classes = get_imagenet_classes()
    imagenet_templates = get_imagenet_templates()

    _, preprocess = clip.load("ViT-B/32")

    vision_model = CLIPVisionModelWithProjection.from_pretrained(
        'openai/clip-vit-base-patch32').cuda()
    tokenizer = CLIPTokenizer.from_pretrained('openai/clip-vit-base-patch32')
    text_model = CLIPTextModelWithProjection.from_pretrained(
        'openai/clip-vit-base-patch32').cuda()

    if poisoned_text_encoder:
        text_model.text_model = poisoned_text_encoder.cuda()

    images = ImageNetV2Dataset(
        variant="matched-frequency", transform=preprocess)
    loader = torch.utils.data.DataLoader(images, batch_size=128, num_workers=0)

    zeroshot_weights = zeroshot_classifier(
        imagenet_classes, imagenet_templates, tokenizer, text_model)

    with torch.no_grad():
        top1, top5, n = 0., 0., 0.
        for images, target in tqdm(loader):
            images = images.cuda()
            target = target.cuda()

            image_features = vision_model(images)[0]
            image_features /= image_features.norm(dim=-1, keepdim=True)
            logits = 100. * image_features @ zeroshot_weights

            acc1, acc5 = accuracy(logits, target, topk=(1, 5))
            top1 += acc1
            top5 += acc5
            n += images.size(0)

    top1 = (top1 / n) * 100
    top5 = (top5 / n) * 100

    print(f"ImageNet-V2 Top-1 accuracy: {top1:.2f}")
    print(f"ImageNet-V2 Top-5 accuracy: {top5:.2f}")
    return top1, top5


def zeroshot_classifier(classnames, templates, tokenizer, text_model):
    with torch.no_grad():
        zeroshot_weights = []
        for classname in tqdm(classnames):
            texts = [template.format(classname)
                     for template in templates]  # format with class
            texts = tokenizer(
                texts,
                padding="max_length",
                max_length=tokenizer.model_max_length,
                truncation=True,
                return_tensors="pt"
            )  # tokenize
            class_embeddings = text_model(texts.input_ids.cuda())[
                0]  # embed with text encoder
            class_embeddings /= class_embeddings.norm(dim=-1, keepdim=True)
            class_embedding = class_embeddings.mean(dim=0)
            class_embedding /= class_embedding.norm()
            zeroshot_weights.append(class_embedding)
        zeroshot_weights = torch.stack(zeroshot_weights, dim=1).cuda()
    return zeroshot_weights


def accuracy(output, target, topk=(1, )):
    pred = output.topk(max(topk), 1, True, True)[1].t()
    correct = pred.eq(target.view(1, -1).expand_as(pred))
    return [float(correct[:k].reshape(-1).float().sum(0, keepdim=True).cpu().numpy()) for k in topk]


def get_imagenet_classes():
    imagenet_classes = [
        "tench",
        "goldfish",
        "great white shark",
        "tiger shark",
        "hammerhead shark",
        "electric ray",
        "stingray",
        "rooster",
        "hen",
        "ostrich",
        "brambling",
        "goldfinch",
        "house finch",
        "junco",
        "indigo bunting",
        "American robin",
        "bulbul",
        "jay",
        "magpie",
        "chickadee",
        "American dipper",
        "kite (bird of prey)",
        "bald eagle",
        "vulture",
        "great grey owl",
        "fire salamander",
        "smooth newt",
        "newt",
        "spotted salamander",
        "axolotl",
        "American bullfrog",
        "tree frog",
        "tailed frog",
        "loggerhead sea turtle",
        "leatherback sea turtle",
        "mud turtle",
        "terrapin",
        "box turtle",
        "banded gecko",
        "green iguana",
        "Carolina anole",
        "desert grassland whiptail lizard",
        "agama",
        "frilled-necked lizard",
        "alligator lizard",
        "Gila monster",
        "European green lizard",
        "chameleon",
        "Komodo dragon",
        "Nile crocodile",
        "American alligator",
        "triceratops",
        "worm snake",
        "ring-necked snake",
        "eastern hog-nosed snake",
        "smooth green snake",
        "kingsnake",
        "garter snake",
        "water snake",
        "vine snake",
        "night snake",
        "boa constrictor",
        "African rock python",
        "Indian cobra",
        "green mamba",
        "sea snake",
        "Saharan horned viper",
        "eastern diamondback rattlesnake",
        "sidewinder rattlesnake",
        "trilobite",
        "harvestman",
        "scorpion",
        "yellow garden spider",
        "barn spider",
        "European garden spider",
        "southern black widow",
        "tarantula",
        "wolf spider",
        "tick",
        "centipede",
        "black grouse",
        "ptarmigan",
        "ruffed grouse",
        "prairie grouse",
        "peafowl",
        "quail",
        "partridge",
        "african grey parrot",
        "macaw",
        "sulphur-crested cockatoo",
        "lorikeet",
        "coucal",
        "bee eater",
        "hornbill",
        "hummingbird",
        "jacamar",
        "toucan",
        "duck",
        "red-breasted merganser",
        "goose",
        "black swan",
        "tusker",
        "echidna",
        "platypus",
        "wallaby",
        "koala",
        "wombat",
        "jellyfish",
        "sea anemone",
        "brain coral",
        "flatworm",
        "nematode",
        "conch",
        "snail",
        "slug",
        "sea slug",
        "chiton",
        "chambered nautilus",
        "Dungeness crab",
        "rock crab",
        "fiddler crab",
        "red king crab",
        "American lobster",
        "spiny lobster",
        "crayfish",
        "hermit crab",
        "isopod",
        "white stork",
        "black stork",
        "spoonbill",
        "flamingo",
        "little blue heron",
        "great egret",
        "bittern bird",
        "crane bird",
        "limpkin",
        "common gallinule",
        "American coot",
        "bustard",
        "ruddy turnstone",
        "dunlin",
        "common redshank",
        "dowitcher",
        "oystercatcher",
        "pelican",
        "king penguin",
        "albatross",
        "grey whale",
        "killer whale",
        "dugong",
        "sea lion",
        "Chihuahua",
        "Japanese Chin",
        "Maltese",
        "Pekingese",
        "Shih Tzu",
        "King Charles Spaniel",
        "Papillon",
        "toy terrier",
        "Rhodesian Ridgeback",
        "Afghan Hound",
        "Basset Hound",
        "Beagle",
        "Bloodhound",
        "Bluetick Coonhound",
        "Black and Tan Coonhound",
        "Treeing Walker Coonhound",
        "English foxhound",
        "Redbone Coonhound",
        "borzoi",
        "Irish Wolfhound",
        "Italian Greyhound",
        "Whippet",
        "Ibizan Hound",
        "Norwegian Elkhound",
        "Otterhound",
        "Saluki",
        "Scottish Deerhound",
        "Weimaraner",
        "Staffordshire Bull Terrier",
        "American Staffordshire Terrier",
        "Bedlington Terrier",
        "Border Terrier",
        "Kerry Blue Terrier",
        "Irish Terrier",
        "Norfolk Terrier",
        "Norwich Terrier",
        "Yorkshire Terrier",
        "Wire Fox Terrier",
        "Lakeland Terrier",
        "Sealyham Terrier",
        "Airedale Terrier",
        "Cairn Terrier",
        "Australian Terrier",
        "Dandie Dinmont Terrier",
        "Boston Terrier",
        "Miniature Schnauzer",
        "Giant Schnauzer",
        "Standard Schnauzer",
        "Scottish Terrier",
        "Tibetan Terrier",
        "Australian Silky Terrier",
        "Soft-coated Wheaten Terrier",
        "West Highland White Terrier",
        "Lhasa Apso",
        "Flat-Coated Retriever",
        "Curly-coated Retriever",
        "Golden Retriever",
        "Labrador Retriever",
        "Chesapeake Bay Retriever",
        "German Shorthaired Pointer",
        "Vizsla",
        "English Setter",
        "Irish Setter",
        "Gordon Setter",
        "Brittany dog",
        "Clumber Spaniel",
        "English Springer Spaniel",
        "Welsh Springer Spaniel",
        "Cocker Spaniel",
        "Sussex Spaniel",
        "Irish Water Spaniel",
        "Kuvasz",
        "Schipperke",
        "Groenendael dog",
        "Malinois",
        "Briard",
        "Australian Kelpie",
        "Komondor",
        "Old English Sheepdog",
        "Shetland Sheepdog",
        "collie",
        "Border Collie",
        "Bouvier des Flandres dog",
        "Rottweiler",
        "German Shepherd Dog",
        "Dobermann",
        "Miniature Pinscher",
        "Greater Swiss Mountain Dog",
        "Bernese Mountain Dog",
        "Appenzeller Sennenhund",
        "Entlebucher Sennenhund",
        "Boxer",
        "Bullmastiff",
        "Tibetan Mastiff",
        "French Bulldog",
        "Great Dane",
        "St. Bernard",
        "husky",
        "Alaskan Malamute",
        "Siberian Husky",
        "Dalmatian",
        "Affenpinscher",
        "Basenji",
        "pug",
        "Leonberger",
        "Newfoundland dog",
        "Great Pyrenees dog",
        "Samoyed",
        "Pomeranian",
        "Chow Chow",
        "Keeshond",
        "brussels griffon",
        "Pembroke Welsh Corgi",
        "Cardigan Welsh Corgi",
        "Toy Poodle",
        "Miniature Poodle",
        "Standard Poodle",
        "Mexican hairless dog (xoloitzcuintli)",
        "grey wolf",
        "Alaskan tundra wolf",
        "red wolf or maned wolf",
        "coyote",
        "dingo",
        "dhole",
        "African wild dog",
        "hyena",
        "red fox",
        "kit fox",
        "Arctic fox",
        "grey fox",
        "tabby cat",
        "tiger cat",
        "Persian cat",
        "Siamese cat",
        "Egyptian Mau",
        "cougar",
        "lynx",
        "leopard",
        "snow leopard",
        "jaguar",
        "lion",
        "tiger",
        "cheetah",
        "brown bear",
        "American black bear",
        "polar bear",
        "sloth bear",
        "mongoose",
        "meerkat",
        "tiger beetle",
        "ladybug",
        "ground beetle",
        "longhorn beetle",
        "leaf beetle",
        "dung beetle",
        "rhinoceros beetle",
        "weevil",
        "fly",
        "bee",
        "ant",
        "grasshopper",
        "cricket insect",
        "stick insect",
        "cockroach",
        "praying mantis",
        "cicada",
        "leafhopper",
        "lacewing",
        "dragonfly",
        "damselfly",
        "red admiral butterfly",
        "ringlet butterfly",
        "monarch butterfly",
        "small white butterfly",
        "sulphur butterfly",
        "gossamer-winged butterfly",
        "starfish",
        "sea urchin",
        "sea cucumber",
        "cottontail rabbit",
        "hare",
        "Angora rabbit",
        "hamster",
        "porcupine",
        "fox squirrel",
        "marmot",
        "beaver",
        "guinea pig",
        "common sorrel horse",
        "zebra",
        "pig",
        "wild boar",
        "warthog",
        "hippopotamus",
        "ox",
        "water buffalo",
        "bison",
        "ram (adult male sheep)",
        "bighorn sheep",
        "Alpine ibex",
        "hartebeest",
        "impala (antelope)",
        "gazelle",
        "arabian camel",
        "llama",
        "weasel",
        "mink",
        "European polecat",
        "black-footed ferret",
        "otter",
        "skunk",
        "badger",
        "armadillo",
        "three-toed sloth",
        "orangutan",
        "gorilla",
        "chimpanzee",
        "gibbon",
        "siamang",
        "guenon",
        "patas monkey",
        "baboon",
        "macaque",
        "langur",
        "black-and-white colobus",
        "proboscis monkey",
        "marmoset",
        "white-headed capuchin",
        "howler monkey",
        "titi monkey",
        "Geoffroy's spider monkey",
        "common squirrel monkey",
        "ring-tailed lemur",
        "indri",
        "Asian elephant",
        "African bush elephant",
        "red panda",
        "giant panda",
        "snoek fish",
        "eel",
        "silver salmon",
        "rock beauty fish",
        "clownfish",
        "sturgeon",
        "gar fish",
        "lionfish",
        "pufferfish",
        "abacus",
        "abaya",
        "academic gown",
        "accordion",
        "acoustic guitar",
        "aircraft carrier",
        "airliner",
        "airship",
        "altar",
        "ambulance",
        "amphibious vehicle",
        "analog clock",
        "apiary",
        "apron",
        "trash can",
        "assault rifle",
        "backpack",
        "bakery",
        "balance beam",
        "balloon",
        "ballpoint pen",
        "Band-Aid",
        "banjo",
        "baluster / handrail",
        "barbell",
        "barber chair",
        "barbershop",
        "barn",
        "barometer",
        "barrel",
        "wheelbarrow",
        "baseball",
        "basketball",
        "bassinet",
        "bassoon",
        "swimming cap",
        "bath towel",
        "bathtub",
        "station wagon",
        "lighthouse",
        "beaker",
        "military hat (bearskin or shako)",
        "beer bottle",
        "beer glass",
        "bell tower",
        "baby bib",
        "tandem bicycle",
        "bikini",
        "ring binder",
        "binoculars",
        "birdhouse",
        "boathouse",
        "bobsleigh",
        "bolo tie",
        "poke bonnet",
        "bookcase",
        "bookstore",
        "bottle cap",
        "hunting bow",
        "bow tie",
        "brass memorial plaque",
        "bra",
        "breakwater",
        "breastplate",
        "broom",
        "bucket",
        "buckle",
        "bulletproof vest",
        "high-speed train",
        "butcher shop",
        "taxicab",
        "cauldron",
        "candle",
        "cannon",
        "canoe",
        "can opener",
        "cardigan",
        "car mirror",
        "carousel",
        "tool kit",
        "cardboard box / carton",
        "car wheel",
        "automated teller machine",
        "cassette",
        "cassette player",
        "castle",
        "catamaran",
        "CD player",
        "cello",
        "mobile phone",
        "chain",
        "chain-link fence",
        "chain mail",
        "chainsaw",
        "storage chest",
        "chiffonier",
        "bell or wind chime",
        "china cabinet",
        "Christmas stocking",
        "church",
        "movie theater",
        "cleaver",
        "cliff dwelling",
        "cloak",
        "clogs",
        "cocktail shaker",
        "coffee mug",
        "coffeemaker",
        "spiral or coil",
        "combination lock",
        "computer keyboard",
        "candy store",
        "container ship",
        "convertible",
        "corkscrew",
        "cornet",
        "cowboy boot",
        "cowboy hat",
        "cradle",
        "construction crane",
        "crash helmet",
        "crate",
        "infant bed",
        "Crock Pot",
        "croquet ball",
        "crutch",
        "cuirass",
        "dam",
        "desk",
        "desktop computer",
        "rotary dial telephone",
        "diaper",
        "digital clock",
        "digital watch",
        "dining table",
        "dishcloth",
        "dishwasher",
        "disc brake",
        "dock",
        "dog sled",
        "dome",
        "doormat",
        "drilling rig",
        "drum",
        "drumstick",
        "dumbbell",
        "Dutch oven",
        "electric fan",
        "electric guitar",
        "electric locomotive",
        "entertainment center",
        "envelope",
        "espresso machine",
        "face powder",
        "feather boa",
        "filing cabinet",
        "fireboat",
        "fire truck",
        "fire screen",
        "flagpole",
        "flute",
        "folding chair",
        "football helmet",
        "forklift",
        "fountain",
        "fountain pen",
        "four-poster bed",
        "freight car",
        "French horn",
        "frying pan",
        "fur coat",
        "garbage truck",
        "gas mask or respirator",
        "gas pump",
        "goblet",
        "go-kart",
        "golf ball",
        "golf cart",
        "gondola",
        "gong",
        "gown",
        "grand piano",
        "greenhouse",
        "radiator grille",
        "grocery store",
        "guillotine",
        "hair clip",
        "hair spray",
        "half-track",
        "hammer",
        "hamper",
        "hair dryer",
        "hand-held computer",
        "handkerchief",
        "hard disk drive",
        "harmonica",
        "harp",
        "combine harvester",
        "hatchet",
        "holster",
        "home theater",
        "honeycomb",
        "hook",
        "hoop skirt",
        "gymnastic horizontal bar",
        "horse-drawn vehicle",
        "hourglass",
        "iPod",
        "clothes iron",
        "carved pumpkin",
        "jeans",
        "jeep",
        "T-shirt",
        "jigsaw puzzle",
        "rickshaw",
        "joystick",
        "kimono",
        "knee pad",
        "knot",
        "lab coat",
        "ladle",
        "lampshade",
        "laptop computer",
        "lawn mower",
        "lens cap",
        "letter opener",
        "library",
        "lifeboat",
        "lighter",
        "limousine",
        "ocean liner",
        "lipstick",
        "slip-on shoe",
        "lotion",
        "music speaker",
        "loupe magnifying glass",
        "sawmill",
        "magnetic compass",
        "messenger bag",
        "mailbox",
        "tights",
        "one-piece bathing suit",
        "manhole cover",
        "maraca",
        "marimba",
        "mask",
        "matchstick",
        "maypole",
        "maze",
        "measuring cup",
        "medicine cabinet",
        "megalith",
        "microphone",
        "microwave oven",
        "military uniform",
        "milk can",
        "minibus",
        "miniskirt",
        "minivan",
        "missile",
        "mitten",
        "mixing bowl",
        "mobile home",
        "ford model t",
        "modem",
        "monastery",
        "monitor",
        "moped",
        "mortar and pestle",
        "graduation cap",
        "mosque",
        "mosquito net",
        "vespa",
        "mountain bike",
        "tent",
        "computer mouse",
        "mousetrap",
        "moving van",
        "muzzle",
        "metal nail",
        "neck brace",
        "necklace",
        "baby pacifier",
        "notebook computer",
        "obelisk",
        "oboe",
        "ocarina",
        "odometer",
        "oil filter",
        "pipe organ",
        "oscilloscope",
        "overskirt",
        "bullock cart",
        "oxygen mask",
        "product packet / packaging",
        "paddle",
        "paddle wheel",
        "padlock",
        "paintbrush",
        "pajamas",
        "palace",
        "pan flute",
        "paper towel",
        "parachute",
        "parallel bars",
        "park bench",
        "parking meter",
        "railroad car",
        "patio",
        "payphone",
        "pedestal",
        "pencil case",
        "pencil sharpener",
        "perfume",
        "Petri dish",
        "photocopier",
        "plectrum",
        "Pickelhaube",
        "picket fence",
        "pickup truck",
        "pier",
        "piggy bank",
        "pill bottle",
        "pillow",
        "ping-pong ball",
        "pinwheel",
        "pirate ship",
        "drink pitcher",
        "block plane",
        "planetarium",
        "plastic bag",
        "plate rack",
        "farm plow",
        "plunger",
        "Polaroid camera",
        "pole",
        "police van",
        "poncho",
        "pool table",
        "soda bottle",
        "plant pot",
        "potter's wheel",
        "power drill",
        "prayer rug",
        "printer",
        "prison",
        "missile",
        "projector",
        "hockey puck",
        "punching bag",
        "purse",
        "quill",
        "quilt",
        "race car",
        "racket",
        "radiator",
        "radio",
        "radio telescope",
        "rain barrel",
        "recreational vehicle",
        "fishing casting reel",
        "reflex camera",
        "refrigerator",
        "remote control",
        "restaurant",
        "revolver",
        "rifle",
        "rocking chair",
        "rotisserie",
        "eraser",
        "rugby ball",
        "ruler measuring stick",
        "sneaker",
        "safe",
        "safety pin",
        "salt shaker",
        "sandal",
        "sarong",
        "saxophone",
        "scabbard",
        "weighing scale",
        "school bus",
        "schooner",
        "scoreboard",
        "CRT monitor",
        "screw",
        "screwdriver",
        "seat belt",
        "sewing machine",
        "shield",
        "shoe store",
        "shoji screen / room divider",
        "shopping basket",
        "shopping cart",
        "shovel",
        "shower cap",
        "shower curtain",
        "ski",
        "balaclava ski mask",
        "sleeping bag",
        "slide rule",
        "sliding door",
        "slot machine",
        "snorkel",
        "snowmobile",
        "snowplow",
        "soap dispenser",
        "soccer ball",
        "sock",
        "solar thermal collector",
        "sombrero",
        "soup bowl",
        "keyboard space bar",
        "space heater",
        "space shuttle",
        "spatula",
        "motorboat",
        "spider web",
        "spindle",
        "sports car",
        "spotlight",
        "stage",
        "steam locomotive",
        "through arch bridge",
        "steel drum",
        "stethoscope",
        "scarf",
        "stone wall",
        "stopwatch",
        "stove",
        "strainer",
        "tram",
        "stretcher",
        "couch",
        "stupa",
        "submarine",
        "suit",
        "sundial",
        "sunglasses",
        "sunglasses",
        "sunscreen",
        "suspension bridge",
        "mop",
        "sweatshirt",
        "swim trunks / shorts",
        "swing",
        "electrical switch",
        "syringe",
        "table lamp",
        "tank",
        "tape player",
        "teapot",
        "teddy bear",
        "television",
        "tennis ball",
        "thatched roof",
        "front curtain",
        "thimble",
        "threshing machine",
        "throne",
        "tile roof",
        "toaster",
        "tobacco shop",
        "toilet seat",
        "torch",
        "totem pole",
        "tow truck",
        "toy store",
        "tractor",
        "semi-trailer truck",
        "tray",
        "trench coat",
        "tricycle",
        "trimaran",
        "tripod",
        "triumphal arch",
        "trolleybus",
        "trombone",
        "hot tub",
        "turnstile",
        "typewriter keyboard",
        "umbrella",
        "unicycle",
        "upright piano",
        "vacuum cleaner",
        "vase",
        "vaulted or arched ceiling",
        "velvet fabric",
        "vending machine",
        "vestment",
        "viaduct",
        "violin",
        "volleyball",
        "waffle iron",
        "wall clock",
        "wallet",
        "wardrobe",
        "military aircraft",
        "sink",
        "washing machine",
        "water bottle",
        "water jug",
        "water tower",
        "whiskey jug",
        "whistle",
        "hair wig",
        "window screen",
        "window shade",
        "Windsor tie",
        "wine bottle",
        "airplane wing",
        "wok",
        "wooden spoon",
        "wool",
        "split-rail fence",
        "shipwreck",
        "sailboat",
        "yurt",
        "website",
        "comic book",
        "crossword",
        "traffic or street sign",
        "traffic light",
        "dust jacket",
        "menu",
        "plate",
        "guacamole",
        "consomme",
        "hot pot",
        "trifle",
        "ice cream",
        "popsicle",
        "baguette",
        "bagel",
        "pretzel",
        "cheeseburger",
        "hot dog",
        "mashed potatoes",
        "cabbage",
        "broccoli",
        "cauliflower",
        "zucchini",
        "spaghetti squash",
        "acorn squash",
        "butternut squash",
        "cucumber",
        "artichoke",
        "bell pepper",
        "cardoon",
        "mushroom",
        "Granny Smith apple",
        "strawberry",
        "orange",
        "lemon",
        "fig",
        "pineapple",
        "banana",
        "jackfruit",
        "cherimoya (custard apple)",
        "pomegranate",
        "hay",
        "carbonara",
        "chocolate syrup",
        "dough",
        "meatloaf",
        "pizza",
        "pot pie",
        "burrito",
        "red wine",
        "espresso",
        "tea cup",
        "eggnog",
        "mountain",
        "bubble",
        "cliff",
        "coral reef",
        "geyser",
        "lakeshore",
        "promontory",
        "sandbar",
        "beach",
        "valley",
        "volcano",
        "baseball player",
        "bridegroom",
        "scuba diver",
        "rapeseed",
        "daisy",
        "yellow lady's slipper",
        "corn",
        "acorn",
        "rose hip",
        "horse chestnut seed",
        "coral fungus",
        "agaric",
        "gyromitra",
        "stinkhorn mushroom",
        "earth star fungus",
        "hen of the woods mushroom",
        "bolete",
        "corn cob",
        "toilet paper"
    ]

    return imagenet_classes


def get_imagenet_templates():
    imagenet_templates = [
        'a bad photo of a {}.',
        'a photo of many {}.',
        'a sculpture of a {}.',
        'a photo of the hard to see {}.',
        'a low resolution photo of the {}.',
        'a rendering of a {}.',
        'graffiti of a {}.',
        'a bad photo of the {}.',
        'a cropped photo of the {}.',
        'a tattoo of a {}.',
        'the embroidered {}.',
        'a photo of a hard to see {}.',
        'a bright photo of a {}.',
        'a photo of a clean {}.',
        'a photo of a dirty {}.',
        'a dark photo of the {}.',
        'a drawing of a {}.',
        'a photo of my {}.',
        'the plastic {}.',
        'a photo of the cool {}.',
        'a close-up photo of a {}.',
        'a black and white photo of the {}.',
        'a painting of the {}.',
        'a painting of a {}.',
        'a pixelated photo of the {}.',
        'a sculpture of the {}.',
        'a bright photo of the {}.',
        'a cropped photo of a {}.',
        'a plastic {}.',
        'a photo of the dirty {}.',
        'a jpeg corrupted photo of a {}.',
        'a blurry photo of the {}.',
        'a photo of the {}.',
        'a good photo of the {}.',
        'a rendering of the {}.',
        'a {} in a video game.',
        'a photo of one {}.',
        'a doodle of a {}.',
        'a close-up photo of the {}.',
        'a photo of a {}.',
        'the origami {}.',
        'the {} in a video game.',
        'a sketch of a {}.',
        'a doodle of the {}.',
        'a origami {}.',
        'a low resolution photo of a {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'a photo of the clean {}.',
        'a photo of a large {}.',
        'a rendition of a {}.',
        'a photo of a nice {}.',
        'a photo of a weird {}.',
        'a blurry photo of a {}.',
        'a cartoon {}.',
        'art of a {}.',
        'a sketch of the {}.',
        'a embroidered {}.',
        'a pixelated photo of a {}.',
        'itap of the {}.',
        'a jpeg corrupted photo of the {}.',
        'a good photo of a {}.',
        'a plushie {}.',
        'a photo of the nice {}.',
        'a photo of the small {}.',
        'a photo of the weird {}.',
        'the cartoon {}.',
        'art of the {}.',
        'a drawing of the {}.',
        'a photo of the large {}.',
        'a black and white photo of a {}.',
        'the plushie {}.',
        'a dark photo of a {}.',
        'itap of a {}.',
        'graffiti of the {}.',
        'a toy {}.',
        'itap of my {}.',
        'a photo of a cool {}.',
        'a photo of a small {}.',
        'a tattoo of the {}.',
    ]
    return imagenet_templates


def get_cifar100_classes():
    return [
        'apple',
        'aquarium fish',
        'baby',
        'bear',
        'beaver',
        'bed',
        'bee',
        'beetle',
        'bicycle',
        'bottle',
        'bowl',
        'boy',
        'bridge',
        'bus',
        'butterfly',
        'camel',
        'can',
        'castle',
        'caterpillar',
        'cattle',
        'chair',
        'chimpanzee',
        'clock',
        'cloud',
        'cockroach',
        'couch',
        'crab',
        'crocodile',
        'cup',
        'dinosaur',
        'dolphin',
        'elephant',
        'flatfish',
        'forest',
        'fox',
        'girl',
        'hamster',
        'house',
        'kangaroo',
        'keyboard',
        'lamp',
        'lawn mower',
        'leopard',
        'lion',
        'lizard',
        'lobster',
        'man',
        'maple tree',
        'motorcycle',
        'mountain',
        'mouse',
        'mushroom',
        'oak tree',
        'orange',
        'orchid',
        'otter',
        'palm tree',
        'pear',
        'pickup truck',
        'pine tree',
        'plain',
        'plate',
        'poppy',
        'porcupine',
        'possum',
        'rabbit',
        'raccoon',
        'ray',
        'road',
        'rocket',
        'rose',
        'sea',
        'seal',
        'shark',
        'shrew',
        'skunk',
        'skyscraper',
        'snail',
        'snake',
        'spider',
        'squirrel',
        'streetcar',
        'sunflower',
        'sweet pepper',
        'table',
        'tank',
        'telephone',
        'television',
        'tiger',
        'tractor',
        'train',
        'trout',
        'tulip',
        'turtle',
        'wardrobe',
        'whale',
        'willow tree',
        'wolf',
        'woman',
        'worm',
    ]


def get_cifar100_templates():
    return [
        'a photo of a {}.',
        'a blurry photo of a {}.',
        'a black and white photo of a {}.',
        'a low contrast photo of a {}.',
        'a high contrast photo of a {}.',
        'a bad photo of a {}.',
        'a good photo of a {}.',
        'a photo of a small {}.',
        'a photo of a big {}.',
        'a photo of the {}.',
        'a blurry photo of the {}.',
        'a black and white photo of the {}.',
        'a low contrast photo of the {}.',
        'a high contrast photo of the {}.',
        'a bad photo of the {}.',
        'a good photo of the {}.',
        'a photo of the small {}.',
        'a photo of the big {}.',
    ]


def get_cifar10_classes():
    return [
        'airplane',
        'automobile',
        'bird',
        'cat',
        'deer',
        'dog',
        'frog',
        'horse',
        'ship',
        'truck',
    ]


def get_cifar10_templates():
    return [
        'a photo of a {}.',
        'a blurry photo of a {}.',
        'a black and white photo of a {}.',
        'a low contrast photo of a {}.',
        'a high contrast photo of a {}.',
        'a bad photo of a {}.',
        'a good photo of a {}.',
        'a photo of a small {}.',
        'a photo of a big {}.',
        'a photo of the {}.',
        'a blurry photo of the {}.',
        'a black and white photo of the {}.',
        'a low contrast photo of the {}.',
        'a high contrast photo of the {}.',
        'a bad photo of the {}.',
        'a good photo of the {}.',
        'a photo of the small {}.',
        'a photo of the big {}.',
    ]


def get_sun_classes():
    return [
        'abbey',
        'airplane cabin',
        'airport terminal',
        'alley',
        'amphitheater',
        'amusement arcade',
        'amusement park',
        'anechoic chamber',
        'apartment building outdoor',
        'apse indoor',
        'aquarium',
        'aqueduct',
        'arch',
        'archive',
        'arrival gate outdoor',
        'art gallery',
        'art school',
        'art studio',
        'assembly line',
        'athletic field outdoor',
        'atrium public',
        'attic',
        'auditorium',
        'auto factory',
        'badlands',
        'badminton court indoor',
        'baggage claim',
        'bakery shop',
        'balcony exterior',
        'balcony interior',
        'ball pit',
        'ballroom',
        'bamboo forest',
        'banquet hall',
        'bar',
        'barn',
        'barndoor',
        'baseball field',
        'basement',
        'basilica',
        'basketball court outdoor',
        'bathroom',
        'batters box',
        'bayou',
        'bazaar indoor',
        'bazaar outdoor',
        'beach',
        'beauty salon',
        'bedroom',
        'berth',
        'biology laboratory',
        'bistro indoor',
        'boardwalk',
        'boat deck',
        'boathouse',
        'bookstore',
        'booth indoor',
        'botanical garden',
        'bow window indoor',
        'bow window outdoor',
        'bowling alley',
        'boxing ring',
        'brewery indoor',
        'bridge',
        'building facade',
        'bullring',
        'burial chamber',
        'bus interior',
        'butchers shop',
        'butte',
        'cabin outdoor',
        'cafeteria',
        'campsite',
        'campus',
        'canal natural',
        'canal urban',
        'candy store',
        'canyon',
        'car interior backseat',
        'car interior frontseat',
        'carrousel',
        'casino indoor',
        'castle',
        'catacomb',
        'cathedral indoor',
        'cathedral outdoor',
        'cavern indoor',
        'cemetery',
        'chalet',
        'cheese factory',
        'chemistry lab',
        'chicken coop indoor',
        'chicken coop outdoor',
        'childs room',
        'church indoor',
        'church outdoor',
        'classroom',
        'clean room',
        'cliff',
        'cloister indoor',
        'closet',
        'clothing store',
        'coast',
        'cockpit',
        'coffee shop',
        'computer room',
        'conference center',
        'conference room',
        'construction site',
        'control room',
        'control tower outdoor',
        'corn field',
        'corral',
        'corridor',
        'cottage garden',
        'courthouse',
        'courtroom',
        'courtyard',
        'covered bridge exterior',
        'creek',
        'crevasse',
        'crosswalk',
        'cubicle office',
        'dam',
        'delicatessen',
        'dentists office',
        'desert sand',
        'desert vegetation',
        'diner indoor',
        'diner outdoor',
        'dinette home',
        'dinette vehicle',
        'dining car',
        'dining room',
        'discotheque',
        'dock',
        'doorway outdoor',
        'dorm room',
        'driveway',
        'driving range outdoor',
        'drugstore',
        'electrical substation',
        'elevator door',
        'elevator interior',
        'elevator shaft',
        'engine room',
        'escalator indoor',
        'excavation',
        'factory indoor',
        'fairway',
        'fastfood restaurant',
        'field cultivated',
        'field wild',
        'fire escape',
        'fire station',
        'firing range indoor',
        'fishpond',
        'florist shop indoor',
        'food court',
        'forest broadleaf',
        'forest needleleaf',
        'forest path',
        'forest road',
        'formal garden',
        'fountain',
        'galley',
        'game room',
        'garage indoor',
        'garbage dump',
        'gas station',
        'gazebo exterior',
        'general store indoor',
        'general store outdoor',
        'gift shop',
        'golf course',
        'greenhouse indoor',
        'greenhouse outdoor',
        'gymnasium indoor',
        'hangar indoor',
        'hangar outdoor',
        'harbor',
        'hayfield',
        'heliport',
        'herb garden',
        'highway',
        'hill',
        'home office',
        'hospital',
        'hospital room',
        'hot spring',
        'hot tub outdoor',
        'hotel outdoor',
        'hotel room',
        'house',
        'hunting lodge outdoor',
        'ice cream parlor',
        'ice floe',
        'ice shelf',
        'ice skating rink indoor',
        'ice skating rink outdoor',
        'iceberg',
        'igloo',
        'industrial area',
        'inn outdoor',
        'islet',
        'jacuzzi indoor',
        'jail cell',
        'jail indoor',
        'jewelry shop',
        'kasbah',
        'kennel indoor',
        'kennel outdoor',
        'kindergarden classroom',
        'kitchen',
        'kitchenette',
        'labyrinth outdoor',
        'lake natural',
        'landfill',
        'landing deck',
        'laundromat',
        'lecture room',
        'library indoor',
        'library outdoor',
        'lido deck outdoor',
        'lift bridge',
        'lighthouse',
        'limousine interior',
        'living room',
        'lobby',
        'lock chamber',
        'locker room',
        'mansion',
        'manufactured home',
        'market indoor',
        'market outdoor',
        'marsh',
        'martial arts gym',
        'mausoleum',
        'medina',
        'moat water',
        'monastery outdoor',
        'mosque indoor',
        'mosque outdoor',
        'motel',
        'mountain',
        'mountain snowy',
        'movie theater indoor',
        'museum indoor',
        'music store',
        'music studio',
        'nuclear power plant outdoor',
        'nursery',
        'oast house',
        'observatory outdoor',
        'ocean',
        'office',
        'office building',
        'oil refinery outdoor',
        'oilrig',
        'operating room',
        'orchard',
        'outhouse outdoor',
        'pagoda',
        'palace',
        'pantry',
        'park',
        'parking garage indoor',
        'parking garage outdoor',
        'parking lot',
        'parlor',
        'pasture',
        'patio',
        'pavilion',
        'pharmacy',
        'phone booth',
        'physics laboratory',
        'picnic area',
        'pilothouse indoor',
        'planetarium outdoor',
        'playground',
        'playroom',
        'plaza',
        'podium indoor',
        'podium outdoor',
        'pond',
        'poolroom establishment',
        'poolroom home',
        'power plant outdoor',
        'promenade deck',
        'pub indoor',
        'pulpit',
        'putting green',
        'racecourse',
        'raceway',
        'raft',
        'railroad track',
        'rainforest',
        'reception',
        'recreation room',
        'residential neighborhood',
        'restaurant',
        'restaurant kitchen',
        'restaurant patio',
        'rice paddy',
        'riding arena',
        'river',
        'rock arch',
        'rope bridge',
        'ruin',
        'runway',
        'sandbar',
        'sandbox',
        'sauna',
        'schoolhouse',
        'sea cliff',
        'server room',
        'shed',
        'shoe shop',
        'shopfront',
        'shopping mall indoor',
        'shower',
        'skatepark',
        'ski lodge',
        'ski resort',
        'ski slope',
        'sky',
        'skyscraper',
        'slum',
        'snowfield',
        'squash court',
        'stable',
        'stadium baseball',
        'stadium football',
        'stage indoor',
        'staircase',
        'street',
        'subway interior',
        'subway station platform',
        'supermarket',
        'sushi bar',
        'swamp',
        'swimming pool indoor',
        'swimming pool outdoor',
        'synagogue indoor',
        'synagogue outdoor',
        'television studio',
        'temple east asia',
        'temple south asia',
        'tennis court indoor',
        'tennis court outdoor',
        'tent outdoor',
        'theater indoor procenium',
        'theater indoor seats',
        'thriftshop',
        'throne room',
        'ticket booth',
        'toll plaza',
        'topiary garden',
        'tower',
        'toyshop',
        'track outdoor',
        'train railway',
        'train station platform',
        'tree farm',
        'tree house',
        'trench',
        'underwater coral reef',
        'utility room',
        'valley',
        'van interior',
        'vegetable garden',
        'veranda',
        'veterinarians office',
        'viaduct',
        'videostore',
        'village',
        'vineyard',
        'volcano',
        'volleyball court indoor',
        'volleyball court outdoor',
        'waiting room',
        'warehouse indoor',
        'water tower',
        'waterfall block',
        'waterfall fan',
        'waterfall plunge',
        'watering hole',
        'wave',
        'wet bar',
        'wheat field',
        'wind farm',
        'windmill',
        'wine cellar barrel storage',
        'wine cellar bottle storage',
        'wrestling ring indoor',
        'yard',
        'youth hostel',
    ]


def get_sun_templates():
    return [
        'a photo of a {}.',
        'a photo of the {}.',
    ]


def get_flowers102_classes():
    return [
        'pink primrose',
        'hard-leaved pocket orchid',
        'canterbury bells',
        'sweet pea',
        'english marigold',
        'tiger lily',
        'moon orchid',
        'bird of paradise',
        'monkshood',
        'globe thistle',
        'snapdragon',
        "colt's foot",
        'king protea',
        'spear thistle',
        'yellow iris',
        'globe flower',
        'purple coneflower',
        'peruvian lily',
        'balloon flower',
        'giant white arum lily',
        'fire lily',
        'pincushion flower',
        'fritillary',
        'red ginger',
        'grape hyacinth',
        'corn poppy',
        'prince of wales feathers',
        'stemless gentian',
        'artichoke',
        'sweet william',
        'carnation',
        'garden phlox',
        'love in the mist',
        'mexican aster',
        'alpine sea holly',
        'ruby-lipped cattleya',
        'cape flower',
        'great masterwort',
        'siam tulip',
        'lenten rose',
        'barbeton daisy',
        'daffodil',
        'sword lily',
        'poinsettia',
        'bolero deep blue',
        'wallflower',
        'marigold',
        'buttercup',
        'oxeye daisy',
        'common dandelion',
        'petunia',
        'wild pansy',
        'primula',
        'sunflower',
        'pelargonium',
        'bishop of llandaff',
        'gaura',
        'geranium',
        'orange dahlia',
        'pink and yellow dahlia',
        'cautleya spicata',
        'japanese anemone',
        'black-eyed susan',
        'silverbush',
        'californian poppy',
        'osteospermum',
        'spring crocus',
        'bearded iris',
        'windflower',
        'tree poppy',
        'gazania',
        'azalea',
        'water lily',
        'rose',
        'thorn apple',
        'morning glory',
        'passion flower',
        'lotus',
        'toad lily',
        'anthurium',
        'frangipani',
        'clematis',
        'hibiscus',
        'columbine',
        'desert-rose',
        'tree mallow',
        'magnolia',
        'cyclamen',
        'watercress',
        'canna lily',
        'hippeastrum',
        'bee balm',
        'air plant',
        'foxglove',
        'bougainvillea',
        'camellia',
        'mallow',
        'mexican petunia',
        'bromelia',
        'blanket flower',
        'trumpet creeper',
        'blackberry lily',
    ]


def get_flowers102_templates():
    return [
        'a photo of a {}, a type of flower.',
    ]


def get_facescrub_classes():
    return [
        'Aaron_Eckhart',
        'Adam_Brody',
        'Adam_McKay',
        'Adam_Sandler',
        'Adrien_Brody',
        'Al_Pacino',
        'Alan_Alda',
        'Alan_Arkin',
        'Alan_Rickman',
        'Alec_Baldwin',
        'Alexander_Skarsgård',
        'Alfred_Molina',
        'Amaury_Nolasco',
        'Andy_Garcia',
        'Andy_Richter',
        'Andy_Serkis',
        'Anthony_Hopkins',
        'Anthony_Stewart_Head',
        'Antonio_Banderas',
        'Arnold_Schwarzenegger',
        'Arnold_Vosloo',
        'Ashton_Kutcher',
        'Ben_Affleck',
        'Ben_Kingsley',
        'Ben_McKenzie',
        'Ben_Stiller',
        'Benicio_Del_Toro',
        'Bernard_Hill',
        'Bernie_Mac',
        'Bill_Cosby',
        'Bill_Hader',
        'Bill_Murray',
        'Bill_Nighy',
        'Billy_Bob_Thornton',
        'Billy_Boyd', 
        'Billy_Burke', 
        'Billy_Zane', 
        'Brad_Garrett', 
        'Brad_Pitt', 
        'Bradley_Cooper', 
        'Brendan_Fraser', 
        'Bruce_Greenwood',
        'Bruce_Willis',
        'Burt_Reynolds',
        'Cam_Gigandet',
        'Cary_Elwes',
        'Casey_Affleck',
        'Channing_Tatum',
        'Charlie_Day',
        'Charlie_Sheen',
        'Chazz_Palminteri',
        'Chris_Evans',
        'Chris_Kattan',
        'Chris_Klein',
        'Chris_Noth',
        'Chris_Rock',
        'Christian_Bale',
        'Christian_Slater',
        'Christopher_Lloyd',
        'Christopher_Reeve',
        'Clint_Eastwood',
        'Clive_Owen',
        'Colin_Farrell',
        'Colin_Firth',
        'Colin_Hanks',
        'Dan_Lauria',
        'Daniel_Craig',
        'Daniel_Day-Lewis',
        'Daniel_Radcliffe',
        'Danny_Glover',
        'Danny_Masterson',
        'Danny_Trejo',
        'David_Boreanaz',
        'David_Cross',
        'David_Duchovny',
        'David_Schwimmer',
        'David_Wenham',
        'Dean_Cain',
        'Denzel_Washington',
        'Dermot_Mulroney',
        'Desmond_Harrington',
        'Diego_Luna',
        'Dominic_Monaghan',
        'Don_Cheadle',
        'Dustin_Hoffman',
        'Dwayne_Johnson',
        'Ed_Harris',
        'Edi_Gathegi',
        'Elijah_Wood',
        'Emile_Hirsch',
        'Eric_Dane',
        'Ethan_Hawke',
        'Ewan_McGregor',
        'Freddie_Prinze_Jr',
        'Freddy_Rodríguez',
        'Gabriel_Macht',
        'Gary_Dourdan',
        'Gary_Oldman',
        'Gene_Hackman',
        'Geoffrey_Rush',
        'George_Clooney',
        'George_Lopez',
        'Gerard_Butler',
        'Giovanni_Ribisi',
        'Hal_Holbrook',
        'Hank_Azaria',
        'Harrison_Ford',
        'Harry_Connick_Jr.',
        'Hayden_Christensen',
        'Heath_Ledger',
        'Hector_Elizondo',
        'Hugh_Grant',
        'Hugh_Jackman',
        'Hugo_Weaving',
        'Ian_Holm',
        'Ian_McKellen',
        'Ioan_Gruffudd',
        'J.K._Simmons',
        'Jack_Nicholson',
        'Jackie_Chan',
        'Jackson_Rathbone',
        'Jaden_Smith',
        'Jake_Gyllenhaal',
        'Jake_Weber',
        'James_Brolin',
        'James_Frain',
        'James_Franco',
        'James_Marsden',
        'James_McAvoy',
        'James_Remar',
        'Jamie_Foxx',
        'Jared_Padalecki',
        'Jason_Bateman',
        'Jason_Behr',
        'Jason_Biggs',
        'Jason_Lee',
        'Jason_Statham',
        'Jason_Sudeikis',
        'Jay_Baruchel',
        'Jean-Claude_Van_Damme',
        'Jean_Reno',
        'Jeffrey_Tambor',
        'Jensen_Ackles',
        'Jeremy_Irons',
        'Jeremy_Sisto',
        'Jerry_Seinfeld',
        'Jesse_Eisenberg',
        'Jet_Li',
        'Jim_Beaver',
        'Jim_Carrey',
        'Jim_Caviezel',
        'Jimmy_Fallon',
        'Joaquin_Phoenix',
        'Joe_Manganiello',
        'Joe_Pantoliano',
        'John_Cleese',
        'John_Cusack',
        'John_Krasinski',
        'John_Malkovich',
        'John_Noble',
        'John_Travolta',
        'Johnny_Depp',
        'Jon_Hamm',
        'Jon_Voight',
        'Jonah_Hill',
        'Jonathan_Rhys_Meyers',
        'Jonathan_Sadowski',
        'Josh_Brolin',
        'Josh_Duhamel',
        'Josh_Hartnett',
        'Joshua_Jackson',
        'Jude_Law',
        'Justin_Long',
        'Justin_Timberlake',
        'Kal_Penn',
        'Karl_Urban',
        'Keanu_Reeves',
        'Kellan_Lutz',
        'Ken_Watanabe',
        'Kerr_Smith',
        'Kevin_Bacon',
        'Kevin_Connolly',
        'Kevin_Costner',
        'Kevin_McKidd',
        'Kiefer_Sutherland',
        'Kit_Harington',
        'Kris_Kristofferson',
        'Laurence_Fishburne',
        'Leonardo_DiCaprio',
        'Leslie_Nielsen',
        'Liev_Schreiber',
        'Luke_Wilson',
        'Mark_Ruffalo',
        'Mark_Wahlberg',
        'Martin_Henderson',
        'Martin_Lawrence',
        'Martin_Sheen',
        'Matt_Czuchry',
        'Matt_Damon',
        'Matt_Dillon',
        'Matt_LeBlanc',
        'Matt_Long',
        'Matthew_Broderick',
        'Matthew_Gray_Gubler',
        'Matthew_Lillard',
        'Matthew_McConaughey',
        'Matthew_Perry',
        'Mel_Gibson',
        'Michael_Douglas',
        'Michael_Landes',
        'Michael_Vartan',
        'Michael_Weatherly',
        'Mike_Myers',
        'Milo_Ventimiglia',
        'Misha_Collins',
        'Neal_McDonough',
        'Nick_Frost',
        'Nicolas_Cage',
        'Norman_Reedus',
        'Oliver_Platt',
        'Omid_Djalili',
        'Orlando_Bloom',
        'Owen_Wilson',
        'Patrick_Dempsey',
        'Patrick_Swayze',
        'Patrick_Warburton',
        'Paul_Bettany',
        'Paul_Walker',
        'Peter_Sarsgaard',
        'Philip_Seymour_Hoffman',
        'Pierce_Brosnan',
        'Ray_Stevenson',
        'Richard_E._Grant',
        'Richard_Gere',
        'Richard_Madden',
        'Richard_Schiff',
        'Rob_Schneider',
        'Robert_De_Niro',
        'Robert_Downey_Jr.',
        'Robert_Duvall',
        'Robert_Knepper',
        'Robert_Patrick',
        'Robert_Pattinson',
        'Robert_Redford',
        'Robin_Williams',
        'Rupert_Friend',
        'Rupert_Grint',
        'Russell_Crowe',
        'Ryan_Gosling',
        'Ryan_Phillippe',
        'Ryan_Reynolds',
        'Sam_Rockwell',
        'Samuel_L._Jackson',
        'Scott_Patterson',
        'Sean_Bean',
        'Seth_Rogen',
        'Shia_LaBeouf',
        'Simon_Pegg',
        'Steve_Carell',
        'T.J._Thyne',
        'Taylor_Lautner',
        'Tobey_Maguire',
        'Tom_Hanks',
        'Victor_Garber',
        'Woody_Allen',
        'Adrianne_León',
        'Adrienne_Barbeau',
        'Adrienne_Frantz',
        'Aisha_Hinds',
        'Alice_Krige',
        'Alley_Mills',
        'Allison_Janney',
        'Alyson_Hannigan',
        'Alyssa_Milano',
        'Amanda_Bearse',
        'America_Ferrera',
        'Amy_Davidson',
        'Andrea_Anders',
        'Andrea_Bogart',
        'Andrea_Bowen',
        'Angell_Conwell',
        'Angie_Harmon',
        'Anne_Hathaway',
        'Annie_Ilonzeh',
        'Ashley_Benson',
        'Ashley_Johnson',
        'Ashley_Jones',
        'Audra_McDonald',
        'Audrey_Landers',
        'Barbara_Carrera',
        'Bobbie_Eakes',
        'Bonnie_Franklin',
        'Brianna_Brown',
        'Brooke_Langton',
        'Calista_Flockhart',
        'Candace_Cameron_Bure',
        'Candice_Bergen',
        'Carey_Lowell',
        'Carla_Gallo',
        'Carmen_Electra',
        'Caroline_Dhavernas',
        'Carolyn_Hennesy',
        'Catherine_Bell',
        'Cathy_Lee_Crosby',
        'Chase_Masterson',
        'Cheryl_Hines',
        'Cheryl_Ladd',
        'Christa_Miller',
        'Christel_Khalil',
        'Christina_Applegate',
        'Christina_Bennett_Lind',
        'Christine_Lakin',
        'Chyler_Leigh',
        'Ciara_Bravo',
        'Courteney_Cox',
        'Crystal_Bernard',
        'Crystal_Chappell',
        'Dana_Delany',
        'Danica_McKellar',
        'Debi_Mazar',
        'Debra_Messing',
        'Delta_Burke',
        'Denise_Crosby',
        'Diahann_Carroll',
        'Dianna_Agron',
        'Didi_Conn',
        'Dina_Meyer',
        'Drea_de_Matteo',
        'Edie_Falco',
        'Eileen_Davidson',
        'Eliza_Coupe',
        'Eliza_Dushku',
        'Elizabeth_Berkley',
        'Elizabeth_Hendrickson',
        'Ellen_DeGeneres',
        'Ellen_Greene',
        'Emily_Deschanel',
        'Erin_Chambers',
        'Erin_Cummings',
        'Eva_Longoria',
        'Faith_Ford',
        'Farah_Fath',
        'Farrah_Fawcett',
        'Felicity_Huffman',
        'Florencia_Lozano',
        'Fran_Drescher',
        'Frances_Fisher',
        'Gabrielle_Carteris',
        'Gates_McFadden',
        'Geena_Davis',
        'Gillian_Anderson',
        'Glenn_Close',
        'Heather_Locklear',
        'Helen_Hunt',
        'Holly_Marie_Combs',
        'Ilene_Kristen',
        'Jackee_Harry',
        'Jamie_Lee_Curtis',
        'Jamie_Luner',
        'Jane_Curtin',
        'Jane_Krakowski',
        'Jane_Leeves',
        'Jane_Lynch',
        'January_Jones',
        'Jasmine_Guy',
        'Jeanne_Cooper',
        'Jenilee_Harrison',
        'Jennette_McCurdy',
        'Jennie_Garth',
        'Jennifer_Aniston',
        'Jennifer_Gareis',
        'Jennifer_Love_Hewitt',
        'Jessica_Biel',
        'Jessica_Capshaw',
        'Jessica_Leccia',
        'Jill_Eikenberry',
        'Jill_Hennessy',
        'Joan_Collins',
        'Joanna_García',
        'Joanna_Kerns',
        'Jodi_Long',
        'Jolene_Blalock',
        'Josie_Bissett',
        'Joyce_DeWitt',
        'Judi_Evans',
        'Judith_Light',
        'Julia_Louis-Dreyfus',
        'Julianna_Margulies',
        'Julie_Benz',
        'Julie_Bowen',
        'Julie_Marie_Berman',
        'Justine_Bateman',
        'Kaley_Cuoco',
        'Kassie_DePaiva',
        'Kate_Linder',
        'Katherine_Helmond',
        'Katherine_Kelly_Lang',
        'Kathryn_Joosten',
        'Kathy_Baker',
        'Kathy_Griffin',
        'Katrina_Bowden',
        'Kellie_Martin',
        'Kim_Cattrall',
        'Kim_Delaney',
        'Kim_Fields',
        'Kimberlin_Brown',
        'Kimberly_Matula',
        'Kimberly_McCullough',
        'Kirstie_Alley',
        'Kristen_Alderson',
        'Kristen_Johnston',
        'Kristian_Alfonso',
        'Kristin_Chenoweth',
        'Kristin_Davis',
        'Kristy_McNichol',
        'Lacey_Chabert',
        'Lara_Flynn_Boyle',
        'Laura_Innes',
        'Laura_Leighton',
        'Lauralee_Bell',
        'Lauren_Holly',
        'Lauren_Koslow',
        'Laurie_Metcalf',
        'Lea_Michele',
        'Lecy_Goranson',
        'Lesley-Anne_Down',
        'Lexi_Ainsworth',
        'Linda_Evans',
        'Linda_Gray',
        'Lindsay_Hartley',
        'Lisa_Bonet',
        'Lisa_Kudrow',
        'Lisa_LoCicero',
        'Loni_Anderson',
        'Lori_Loughlin',
        'Lorraine_Bracco',
        'Lourdes_Benedicto',
        'Mackenzie_Aladjem',
        'Marcia_Cross',
        'Marg_Helgenberger',
        'Margaret_Cho',
        'Mariel_Hemingway',
        'Marilu_Henner',
        'Mary_Beth_Evans',
        'Mary_Crosby',
        'Mayim_Bialik',
        'McKayla_Maroney',
        'Melina_Kanakaredes',
        'Melissa_Archer',
        'Melissa_Benoist',
        'Melissa_Claire_Egan',
        'Melissa_Fumero',
        'Melissa_Gilbert',
        'Mila_Kunis',
        'Miranda_Cosgrove',
        'Molly_Burnett',
        'Morena_Baccarin',
        'Nadia_Bjorlin',
        'Nancy_Lee_Grahn',
        'Natalia_Livingston',
        'Natalie_Hall',
        'Natalie_Martinez',
        'Neve_Campbell',
        'Nicole_Eggert',
        'Nicole_de_Boer',
        "Olivia_d'Abo", 'Pamela_Anderson',
        'Pamela_Sue_Martin',
        'Patricia_Arquette',
        'Patricia_Kalember',
        'Peggy_Lipton',
        'Peggy_McCay',
        'Peri_Gilpin',
        'Portia_Doubleday',
        'Portia_de_Rossi',
        'Rachel_Dratch',
        'Rachel_Griffiths',
        'Rebecca_Budig',
        'Rebecca_Herbst',
        'Roma_Downey',
        'Roseanne_Barr',
        'Rue_McClanahan',
        'S._Epatha_Merkerson',
        'Sally_Field',
        'Sara_Gilbert',
        'Sarah_Chalke',
        'Sarah_Drew',
        'Sarah_Hyland',
        'Sarah_Michelle_Gellar',
        'Sasha_Alexander',
        'Selena_Gomez',
        'Shannen_Doherty',
        'Shannon_Kane',
        'Sharon_Case',
        'Sharon_Gless',
        'Shelley_Hack',
        'Shelley_Hennig',
        'Shelley_Long',
        'Sherilyn_Fenn',
        'Shirley_Jones',
        'Staci_Keanan',
        'Stana_Katic',
        'Summer_Glau',
        'Susan_Dey',
        'Susan_Flannery',
        'Susan_Lucci',
        'Swoosie_Kurtz',
        'Tamala_Jones',
        'Tamara_Braun',
        'Tatyana_Ali',
        'Taylor_Atelian',
        'Tempestt_Bledsoe',
        'Teri_Hatcher',
        'Terry_Farrell',
        'Tia_Carrere',
        'Tina_Fey',
        'Tina_Louise',
        'Tracey_E._Bregman',
        'Tracey_Gold',
        'Tyne_Daly',
        'Valerie_Bertinelli',
        'Valerie_Cruz',
        'Valerie_Harper',
        'Vanessa_Marcil',
        'Veronica_Hamel',
        'Victoria_Justice',
        'Wanda_De_Jesus',
        'Wendie_Malick',
        'Yasmine_Bleeth',
        'Zooey_Deschanel'
    ]


def get_facescrub_templates():
    return [
    '{}',
    'an image of {}',
    'a photo of {}',
    '{} on a photo',
    'a photo of a person named {}',
    'a person named {}',
    'a man named {}',
    'a woman named {}',
    'the name of the person is {}',
    'a photo of a person with the name {}',
    '{} at a gala',
    'a photo of the celebrity {}',
    'actor {}',
    'actress {}',
    'a colored photo of {}',
    'a black and white photo of {}',
    'a cool photo of {}',
    'a cropped photo of {}',
    'a cropped image of {}',
    '{} in a suit',
    '{} in a dress'
    ]
