defaults:
    - idia: defaults
    - facescrub: defaults
    - concept_removal: defaults
    - _self_

open_clip:
    model_name: 'ViT-B-32'
    pretrained_weights_name: 'laion400m_e32'
seed: 42

wandb:
    entity: null
    experiment_name: 'Defending_With_Backdoors'
    run_name: ${concept_removal.backdoor_injection.number_of_backdoors} IDs, ${concept_removal.backdoor_injection.min_num_correct_maj_preds_for_injection} Threshold
    offline: false
    project: 'Defending_With_Backdoors'
    save_model: true
    use_wandb: false

